const toDoItems = [
  {
    id: 1,
    todo: "Go grocery shopping",
    complete: false,
  },
  {
    id: 2,
    todo: "Complete the React project",
    complete: false,
  },
  {
    id: 3,
    todo: "Exercise for 30 minutes",
    complete: false,
  },
  {
    id: 4,
    todo: "Call mom",
    complete: false,
  },
  {
    id: 5,
    todo: "Read for one hour",
    complete: false,
  },
  {
    id: 6,
    todo: "Clean the kitchen",
    complete: false,
  },
];

export default toDoItems;